### ISSUE TITLE
channeldb+routing+htlcswitch: extract payment tracking from rpcserver, unify in router+switch

### ISSUE THREAD

**Issue by Roasbeef** [lightningnetwork/lnd#2183]
Tracking of outgoing payments within `lnd` currently has a number of bugs:
  * If a payment is initiated, but `lnd` crashes before it's complete, even once the pre-image comes back, we'll never mark it as fully settled in the database.
  * If a user uses the streaming RPC, and a payment is initiated, but the client is closed before it completes, then we'll again not even create the payment within the database. 
  * It's possible for two concurrent sending attempts from clients to flip-flop the control tower state during retries. 

Both of the bugs above stem from the fact that we _only_ write the payment in the same goroutines that creates the payment. To solve this, we need to move the payment tracking into the two sub-systems that will always be around when the payment is created (`ChannelRouter`) and ultimately settled (`HtlcSwitch`). 

While we're at it, we can also implement a much requested feature: for instances of `SendPayment` to be idempotent. Namely, once a payment has already been completed, a call to `SendPayment` with the same payment hash and amount should return the pre-image and final route from the database just as if it had _just_ completed. Additionally, it should be possible to _cancel_ an in-flight payment, which marks it as dead, so the channel router no longer attempts to satisfy the payment requirements. Finally, if a call to `SendPayment` is issued, and a payment with the same payment hash is in-flight, it should block until completed. 

# Steps To Completion 

- [x] Move _creation_ of the payment state into the `ChannelRouter` after each payment attempt. This way, we can properly track the last route used, as well as the fees, which won't be known to the switch at payment time. If a payment ends in an unsatisfied state (timeout, or no route), then it should be marked as such in the database. 

- [x] Move finalization of a payment's state into the `HtlcSwitch`, once a payment comes back across, we attempt to look up the sender in an in-memory map. In the idea case (before these changes) an entry is within the map, however, if the daemon has re-started, then we won't find anything in this map. Instead, another case needs to be added to dispatch the payment (via a new callback/interface perhaps) back to the primary caller. 

- [x] Within `SendPayment`, check the payment database to see if a payment for this payment hash was already completed. If so, just return the existing payment, possibly with fields indicating that this is the state from a _prior_ attempt. 

- [ ] Add pending payment attempt tracking to the `ChannelRouter` so we can cancel payments with a new RPC call. 

- [ ] With the payment tracking moved into the client, if a timeout hasn't been hit, then we can continue to retry a payment attempt in the background after a restart.

**Comment by joostjager** [comment]
I noticed that SendPayment first checks an invoice for expiry and only if it hasn't expired yet, it may find out in `htlcswitch` that is was already paid.

For idempotent behaviour, SendPayment should in this case return ErrAlreadyPaid instead of 'invoice expired'.

**Comment by joostjager** [comment]
>Within SendPayment, check the payment database to see if a payment for this payment hash was already completed. If so, just return the existing payment, possibly with fields indicating that this is the state from a prior attempt.

In case the payment is already completed, it should also return the used route (as if this was the first time the call was made). Otherwise we cannot figure out how many fees were paid for this payment.

**Comment by treygriffith** [comment]
> This way, we can properly track the last route used, as well as the fees, which won't be known to the switch at payment time. If a payment ends in an unsatisfied state (timeout, or no route), then it should be marked as such in the database.

@Roasbeef does this change contemplate separating the notion of a payment from a payment attempt within the database?

**Comment by joostjager** [comment]
I ran into the following requirement: idempotent sendpayment, but only if it was already started.

**Comment by Roasbeef** [comment]
Has now been resolved, other than the cancel payment portion, as upon restart we'll only try once. Will make a new issue to track the cancel option.
