### ISSUE TITLE
channeldb: master tracking disk-space reduction issue

### ISSUE THREAD

**Issue by Roasbeef** [lightningnetwork/lnd#5388]
Our default database backend (boltdb) by default doesn't automatically reclaim (release back to the OS) disk space. Instead any time something is deleted, the page will (eventually) go into a freelist for pages to use at a later point. The process of compaction simply inserts all keys into a new database, which results in a disk space reduction given that the old freelist pages aren't copied over to the new database. 

Over time, due to the bucket structure of boltdb, very large buckets start to degrade performance as inserting [entails an `O(N)` operation when pages need to be split/spilled](https://github.com/boltdb/bolt/blob/fd01fc79c553a8e99d512a07e8e0c63d4a3ccfc5/bucket.go#L528). Within the codebase atm, there're several areas where we keep around state simply because its convenient when instead we could make a space vs time tradeoff and re-compute (at times needing to brute force) the state when we need it.

This is a master-tracking issue for any disk-space reduction optimizations that are either in-progress or planned: 
  

- [x] Remove the [append-only update log associated with all channels](https://github.com/lightningnetwork/lnd/blob/42099ef5e1e0f927290531fe2bff18406141567b/channeldb/channel.go#L3644). This grows forever until a channel is fully closed. In the future operations like splicing would let us shed this data. The only reason we keep this around is to be able to [quickly look up the offending state during a breach](https://github.com/lightningnetwork/lnd/blob/1868c7dec180269db00386b7c0f09e8d45dab5c2/lnwallet/channel.go#L2291). 
    * If this is removed, then we may want a mode that _optionally_ retains it, as it can be useful to do things like generate a complete audit report of every state transition that has ever happend. 
     * If removed, then instead of looking up the state number, we'll need to instead brute force the HTLC information, and rely on the transaction itself for the fee rate and balances at that state. 
  
- [x] Clean up the forwarding state when channels are closed, on going work in this PR: https://github.com/lightningnetwork/lnd/pull/4364
- [x] Only keep around failed payment attempts if specified by a new flag. This is a major culprit of ballooning database state as due to things like payment splitting a succesful attempt may generate several failures. 
- [x] Blank out any on-disk onion blobs if specified with a new flag. Each blob is 1.3 KB and we store them several times over in places like payment attempts as well as invoices.

**Comment by Roasbeef** [comment]
Related comment/issue: https://github.com/lightningnetwork/lnd/issues/3703#issuecomment-552665524

**Comment by saubyk** [comment]
Hi @Roasbeef can we include ability to delete expired (unpaid) invoices as well in the list above?

**Comment by Roasbeef** [comment]
@saubyk that already exists: https://github.com/lightningnetwork/lnd/blob/master/sample-lnd.conf#L396

**Comment by Roasbeef** [comment]
Related issue: https://github.com/lightningnetwork/lnd/issues/3703

**Comment by Roasbeef** [comment]
Last items was fixed by https://github.com/lightningnetwork/lnd/pull/6469
