### ISSUE TITLE
[Epic] channeldb+invoices: create native SQL schema for invoice storage

### ISSUE THREAD

**Issue by Roasbeef** [lightningnetwork/lnd#6288]
We recently added postgres support, but in a way that just maps things to a naive key-value table. In order to take advantage of increased queryability, and scalability gains, we should convert the invoices (which can be heavily loaded on large nodes that help to operate services) to a native SQL schema. Along the way, we'll want to abstract away the invoice registry's storage behind an interface, so this new data format can be swapped in at runtime, or during initial configuration of the daemon. 

# Steps to Completion
- [x] #6842
- [x] #6954
- [x] Create a new SQL-native invoice schema. 
   * Tools like `sqlc` look interesting here as it lets you mainly write SQL in a single file, and have the CRUD code be generated. We use this in some backend products at Lightning Labs now. 
   * Alternatively, since `sqlc` doesn't support sqlite fully (though I think if you don't use any sqlite specific features it works), we could look into using other ORMs. 
- [x] Implement a migration tool to be run automatically given a relevant set of flags, or manually via a migrate-then-shutdown flag/script. 
- [x] https://github.com/lightningnetwork/lnd/issues/9434

Related to:
  * #6176
  
  - Create a new SQL-native invoice schema:
      * #7343
      * #7354
      ~~* #7357~~
      * #8052

**Comment by bitromortac** [comment]
Started to look into the first two points as of assignment to #6954.

**Comment by guggero** [comment]
Re-opening since one part is still missing (will link when PR is up).

**Comment by ZZiigguurraatt** [comment]
Seems like everything in this issue is now done?

**Comment by guggero** [comment]
Agree. Or what do you think, @saubyk?

**Comment by saubyk** [comment]
Yup.
