### ISSUE TITLE
[epic]: Gossip 1.75

### ISSUE THREAD

**Issue by ellemouton** [lightningnetwork/lnd#7961]
This issue will be used to track the progress of spec proposal and LND implementation of Gossip 1.75.

### Useful Links

- Draft spec proposal: https://github.com/lightning/bolts/pull/1059
- Upcoming spec draft updates: https://github.com/lightning/bolts/pull/1059#issuecomment-1638736026

### Plan

- [ ] Spend some time understanding how LND handles Gossip today
- [ ] Update the spec proposal with the latest updates
- [ ] Flesh out: Handling of old & new gossip messages (ie, when does it make sense to stop sending old node announcement etc)
- [ ] Flesh out: nonce generation for `announcement_sigs_2`
- [ ] Flesh out gossip query updates
- [ ] Code for handling new received `channel_announcement_2`
- [ ] Code for handling new received `channel_update_2`
- [ ] Code for handling new received `node_announcement_2`
- [ ] Code for creating new `node_announcement_2`
- [ ] Code for creating new `channel_announcement_2` in the funding manager 
- [ ] Code for creating new `channel_update`
- [ ] Update code for handling gossip queries

**Comment by ellemouton** [comment]
outdated. Soon to be replaced
