### ISSUE TITLE
tracking: remaining cleanup to address before merging `0-19-staging` branch into master

### ISSUE THREAD

**Issue by guggero** [lightningnetwork/lnd#8769]
This issue tracks all cleanup that is necessary to address before we can merge the `0-19-staging` branch into master.

 - [x] https://github.com/lightningnetwork/lnd/pull/8509#discussion_r1606975757 (collision and range of custom local SCID aliases)
 - [x] https://github.com/lightningnetwork/lnd/pull/8509#discussion_r1588119871 (error handling for unknown custom local SCID alias)
 - [x] https://github.com/lightningnetwork/lnd/pull/8509#issuecomment-2120858347 (collision detection and validation of base SCID)
 - [x] https://github.com/lightningnetwork/lnd/pull/8660#discussion_r1608641948 (implement and test HTLC custom record persistence)
 - [x] https://github.com/lightningnetwork/lnd/pull/8660#discussion_r1609843872 (unit test coverage of all added custom record functionality)
 - [x] https://github.com/lightningnetwork/lnd/pull/8660#discussion_r1606720575 (persistence of custom records across restarts when sending payments)
 - [x] https://github.com/lightningnetwork/lnd/pull/8632#discussion_r1612091616 (mock implementation for aux components and basic unit test coverage)
 - [X] https://github.com/lightningnetwork/lnd/pull/8771#discussion_r1616920049 (add more fields to `invoicesrpc.HtlcModifier`
    - Marked as done because no additional fields were required for the custom channel functionality.
 - [x] revert itest change in https://github.com/lightningnetwork/lnd/pull/8908/commits/4f2c75f62047579f249ed5914042a0cc6337f342 to properly test amount modification
     - Need to use invoice acceptor to be able to pull this off, so create invoice for amount X, actually send X*2 (which'll be in the MPP amount to expect), intercept HTLC to modify it back to X then use invoice acceptor to settle with just X and ignore MPP total amount)
- [x] https://github.com/lightningnetwork/lnd/pull/8960#discussion_r1717776047 (remove hardcoded sweep output amount)
